Crowdcams/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'CommunityCams.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'', include('web_app.urls', namespace='web_app')),
    url(r'^admin/', include(admin.site.urls)),
)

web_app/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from web_app import views

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'CommunityCams.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^$', views.home, name='home'),
                       url(r'list/$', views.list, name='listing'),
                       url(r'^protectyourneighborhood/$', views.protect_your_neighborhood,
                           name='protect_your_neighborhood'),
                       url(r'^protectyourneighborhood/newpost$', views.new_post, name='new_post'),
                       url(r'^howitworks/$', views.how_it_works, name='how_it_works'),
                       url(r'^projectfounders/$', views.project_founders, name='project_founders'),
                       url(r'^ourvision/$', views.our_vision, name='our_vision'),
                       url(r'^accounts/register/$', views.register, name='user_registration'),
                       url(r'^accounts/login/$', views.login, name='user_login'),
                       url(r'^view/$', views.view_stream, name='view_stream'),
                       url(r'^apps/regions/$', views.app_regions, name='app_regions'),
                       url(r'^apps/smiles/$', views.app_smiles, name='app_smiles')
)

templates/app_regions.html
{% extends "base_template.html" %}

{% block content %}
    {% load static %}
    <div id="content_sec">
        <script type="application/javascript" src="{% static 'js/raphael-min.js' %}"></script>
        <!--Main Section-->
        <div class="col1">
            <div class="vediocontainer">
                <h2 class="pd11">Monitor Virtual Regions</h2>

                <div class="vedioactive">
                    <div id="video_canvas" style="cursor: crosshair;width: 651px;height: 398px;position: absolute; z-index: 1000;"></div>
                    <object class="flashobj" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
                            id="utv510050"
                            style="width:651px; height:398px; z-index: -1000;">
                        <param name="flashvars"
                               value="autoplay=false&amp;brand=embed&amp;cid={{ stream.ustream_uid }}"/>
                        <param name="allowfullscreen" value="true"/>
                        <param name="allowscriptaccess" value="always"/>
                        <param name="movie" value="http://www.ustream.tv/flash/viewer.swf"/>
                        <embed flashvars="autoplay=true&amp;brand=embed&amp;cid={{ stream.ustream_uid }}"
                               allowfullscreen="true" allowscriptaccess="always"
                               id="{{ stream.ustream_uid }}embed"
                               name="utv_n_41439" src="http://www.ustream.tv/flash/viewer.swf"
                               type="application/x-shockwave-flash"
                               style="width: inherit;height: inherit;"/>
                    </object>
                </div>
                <div class="sharevedio">
                    <div class="sv_topsec">
                        <div class="like_dislike">
                            <ul>
                                <li><a class="like" href="#">Like</a></li>
                                <li class="nobdr"><a class="dslike" href="#">Dislike</a></li>
                            </ul>
                        </div>
                        <a href="#" class="sharetab">Share</a>

                        <div class="embed"><a href="#" class="embed">Embed</a></div>
                        <a class="add_to" href="#">Add to</a>

                        <div class="shareonbg"><a class="link1" href="#">200</a></div>
                        <div class="shareonbg"><a class="link2" href="#">200</a></div>
                        <div class="shareonbg"><a class="link3" href="#">200</a></div>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
                <div class="cmntcontainer">
                    <h2 class="pd11">Comments</h2>

                    <div class="comment">
                        <textarea class="txtcomment" name="txt" cols="0" rows="0"></textarea>
                    </div>
                    <div class="clear"></div>
                    <div class="commentaction">
                        <span class="left">500 characters remaining</span>
                        <ul>
                            <li><a href="#">Cancel</a> or</li>
                            <li><a class="post" href="#">post</a></li>
                            <li class="nomar"><a class="vedio" href="#">Attach a video</a></li>
                        </ul>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <!--Right Section-->
        <div class="col2">
            <!--Feature Vedio -->
            <div class="sideblock2">
                <h2>Your Apps</h2>
                <ul>
                    <li>
                        <div class="thumb">
                            <a href="#">
                                <img src="{% static 'images/featurevideo1.jpg' %}" alt=""/>
                            </a>
                        </div>
                        <div class="description">
                            <p><a href="/apps/regions/?vid={{ stream.ustream_uid }}"> Virtual Regions</a></p>

                            <p class="viewcounts">Create and monitor virtual regions on your streams</p></p>
                        </div>
                    </li>
                    <li>
                        <div class="thumb">
                            <a href="detail.html">
                                <img src="{% static 'images/featurevideo2.jpg' %}" alt=""/>
                            </a>
                        </div>
                        <div class="description">
                            <p><a href="/apps/smiles/?vid={{ stream.ustream_uid }}"> Smile Detection</a></p>

                            <p class="viewcounts">Lets you know whenever someone smiled</p></div>
                    </li>
                </ul>
                <div class="clear"></div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <script type="application/javascript">
        (function () {
            'use strict';

            // Get the absolute position of a particular object on the page
            // Source: http://www.quirksmode.org/js/findpos.html
            function findPos(obj) {
                var curleft = 0, curtop = 0;
                if (obj.offsetParent) {
                    do {
                        curleft += obj.offsetLeft;
                        curtop += obj.offsetTop;
                    } while (obj = obj.offsetParent);
                    return [curleft, curtop];
                } else {
                    return false;
                }
            }

            // Get the current position of the mouse, relative to the page
            function getCoords(event) {
                event = event || window.event;
                if (event.pageX || event.pageY) {
                    return {x: event.pageX, y: event.pageY};
                }
                return {
                    x: event.clientX + document.body.scrollLeft - document.body.clientLeft,
                    y: event.clientY + document.body.scrollTop - document.body.clientTop
                };
            }

            // Draw the shape based on the current coordinates and position at onmousedown
            function doDraw(event) {
                if (rect) {
                    var mousePos = getCoords(event);
                    var currentX = mousePos.x - offset[0];
                    var currentY = mousePos.y - offset[1];
                    var width = currentX - startX;
                    var height = currentY - startY;

                    if (width < 0) {
                        rect.attr({'x': currentX, 'width': width * -1});
                    } else {
                        rect.attr({'x': startX, 'width': width});
                    }
                    if (height < 0) {
                        rect.attr({'y': currentY, 'height': height * -1});
                    } else {
                        rect.attr({'y': startY, 'height': height});
                    }
                }
            }

            // Global variables
            var div_paper = document.getElementById('video_canvas');
            var paper = new Raphael('video_canvas');
            var rect;
            var startX = 0, startY = 0;
            var offset = findPos(div_paper);

            div_paper.onmousedown = function (event) {
                var mouseCoords = getCoords(event);
                startX = mouseCoords.x - offset[0];
                startY = mouseCoords.y - offset[1];
                rect = paper.rect(startX, startY, 0, 0);
                rect.attr("stroke", "#FFFF00");
                document.onmousemove = doDraw;
            };

            div_paper.onmouseup = function (event) {
                var region_name = '';
                document.onmousemove = null;
                while(region_name == ''){
                    region_name = prompt("Enter a name for the region:");
                }
                $.ajax({
                    url: "{% url 'web_app:app_regions' %}",
                    data: {
                        'x': rect.attr('x'),
                        'y': rect.attr('y'),
                        'width': rect.attr('width'),
                        'height': rect.attr('height'),
                        'region': region_name,
                        'stream_url': "{{ stream.url }}"
                    },
                    type: "POST",
                    dataType: 'json'
                }).done(function(data){
                    if(data.status == 'true'){
                        alert("Started monitoring: " + region_name);
                    }
                    else{
                        alert("Failed to setup monitoring");
                    }
                }).fail(function(jqXHR, status, error){
                    alert("Couldn't connect to server");
                })

            };
        })();
    </script>

    <div class="clear"></div>
{% endblock %}

templates/app_smiles.html
{% extends "base_template.html" %}

{% block content %}
    {% load static %}
    <div id="content_sec">

    <!--Main Section-->
    <div class="col1">
        <div class="vediocontainer">
            <h2 class="pd11">Most Popular Videos</h2>

            <div class="vedioactive">
                <object class="flashobj" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
                        id="utv510050"
                        style="width:651px; height:398px; z-index: -1000;">
                    <param name="flashvars"
                           value="autoplay=false&amp;brand=embed&amp;cid={{ stream.ustream_uid }}"/>
                    <param name="allowfullscreen" value="true"/>
                    <param name="allowscriptaccess" value="always"/>
                    <param name="movie" value="http://www.ustream.tv/flash/viewer.swf"/>
                    <embed flashvars="autoplay=true&amp;brand=embed&amp;cid={{ stream.ustream_uid }}"
                           allowfullscreen="true" allowscriptaccess="always"
                           id="{{ stream.ustream_uid }}embed"
                           name="utv_n_41439" src="http://www.ustream.tv/flash/viewer.swf"
                           type="application/x-shockwave-flash"
                           style="width: inherit;height: inherit;"/>
                </object>
            </div>
            <div class="sharevedio">
                <div class="sv_topsec">
                    <div class="like_dislike">
                        <ul>
                            <li><a class="like" href="#">Like</a></li>
                            <li class="nobdr"><a class="dslike" href="#">Dislike</a></li>
                        </ul>
                    </div>
                    <a href="#" class="sharetab">Share</a>

                    <div class="embed"><a href="#" class="embed">Embed</a></div>
                    <a class="add_to" href="#">Add to</a>

                    <div class="shareonbg"><a class="link1" href="#">200</a></div>
                    <div class="shareonbg"><a class="link2" href="#">200</a></div>
                    <div class="shareonbg"><a class="link3" href="#">200</a></div>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <div class="cmntcontainer">
                <h2 class="pd11">Comments</h2>

                <div class="comment">
                    <textarea class="txtcomment" name="txt" cols="0" rows="0"></textarea>
                </div>
                <div class="clear"></div>
                <div class="commentaction">
                    <span class="left">500 characters remaining</span>
                    <ul>
                        <li><a href="#">Cancel</a> or</li>
                        <li><a class="post" href="#">post</a></li>
                        <li class="nomar"><a class="vedio" href="#">Attach a video</a></li>
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <!--Right Section-->
    <div class="col2">
        <!--Feature Vedio -->
        <div class="sideblock2">
            <h2>Your Apps</h2>
            <ul>
                <li>
                    <div class="thumb">
                        <a href="#">
                            <img src="{% static 'images/featurevideo1.jpg' %}" alt=""/>
                        </a>
                    </div>
                    <div class="description">
                        <p><a href="/apps/regions/?vid={{ stream.ustream_uid }}"> Virtual Regions</a></p>

                        <p class="viewcounts">Create and monitor virtual regions on your streams</p></p>
                    </div>
                </li>
                <li>
                    <div class="thumb">
                        <a href="detail.html">
                            <img src="{% static 'images/featurevideo2.jpg' %}" alt=""/>
                        </a>
                    </div>
                    <div class="description">
                        <p><a href="/apps/smiles/?vid={{ stream.ustream_uid }}"> Smile Detection</a></p>

                        <p class="viewcounts">Lets you know whenever someone smiled</p></div>
                </li>
            </ul>
            <div class="clear"></div>
        </div>
    </div>
    <div class="clear"></div>
    </div>


    <div class="clear"></div>
{% endblock %}

templates/howitworks.html
{% extends "base_template.html" %}
{% block content %}
    {% load static %}
	<!--Content Sec -->
	<div id="content_sec">
        <!--Main Section-->
		<div class="hero_3" id="running-board-wrap">
			<div class="container" id="running-board">
				<div id="howitworks_image"></div>
					<div id="hero">
						<p class="big_type">&nbsp;&nbsp;Crowdsourcing security to<br>make this world a safer place</p>
					</div>
					<div class="container" id="s-board">
					</div>
				</div>
			</div>
			<div class="container" id="written_content">
				<div class="interior">
				<div class="group2" style="padding-bottom: 0px">
					<p><i style="color: #000000"> Spend some free time watching one or more live video streams at Crowdcams and report any suspicious activity. Share a live stream of a location nearby you and enable others to monitor it.</i></p>
				</div>
				<h2 style="font-size:24px">Do something good today!</h2>
				<div class="group2">
					<p class="small_type">&nbsp;&nbsp;&nbsp;&nbsp;Find live streams originating at locations near you and around the world. Choose one or more to watch and monitor the movements. Report any suspicious activities via a simple phone call to the local authority's contact number given along with each stream. <br>
						It's that simple, but believe us, you may end up stopping an armed robbery, getting a drunk driver arrested, facilitating a drug racket bust or even saving a life or maybe many lives.
					</p>
				</div>
				<h2 style="font-size:24px">Stop crimes by broadcasting</h2>
				<div class="group2">
					<p class="small_type">&nbsp;&nbsp;&nbsp;&nbsp;Have a neighborhood location in your mind you feel is unsafe. Install a webcam pointing at it and give us the live stream.
						Once online at Crowdcams, the location could be monitored by the dwellers of your neighborhood as well as other active Crowdcams users around the world. Such monitoring may greatly help in protecting the location against criminal activities described above amongst others.
						</p></div>
							
							<h2 style="font-size:24px">Steps to share</h2>
							<div class="group2">
						<p class="small_type">&nbsp;&nbsp;&nbsp;&nbsp;
					To share a live video feed, visit our partner <a href="http://www.ustream.tv">Ustream</a>. At the Ustream homepage, select Go live! and follow the steps.
                        <br>Once the live stream starts broadcasting, just copy your channel URL(something like http://www.ustream.tv/channel/your-channel-name-here) at the <a href="/protectyourneighborhood">Protect Your Neighbourhood</a> page, provide the details of the location your channel is broadcasting and a phone number. This should be the phone number of the local authority ex. Local Police Station, that must be contacted in case one of our users notices a suspicious activity at your channel. As you submit, we will instantly fetch the live stream and list it at Crowdcams.                       
					</p>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/index.html
{% extends "base_template.html" %}

{% block content %}
    {% load static %}
    <!--Content Sec -->
    <div id="content_sec">
        <!--Main Section-->
        <div class="container" id="written_content">

            <div class="home_welcome">
                <ul>
                    <li style="color: #202b19; text-align: center"><i>Crowdcams enables everyone to contribute in reducing crime<br> Share and monitor live video streams of public areas, report suspicious activities and start making a difference now</i></li>
                </ul>
            </div>
        </div>
        <div class="col1">
            <!--Video slider -->
            <div class="mostcontainer">
                <h2>Featured Locations</h2>
                <ul>

                    {% for stream in streams %}
                        <li>
                            <div class="vediodiv">
                                <div id="{{ stream.ustream_uid }}div" class="light_div" data-title="{{ stream.title }}"
                                     data-uid="{{ stream.ustream_uid }}" data-loc="{{ stream.location_description }}"
                                     data-contact="{{ stream.emergency_contact }}"
                                     style="width: inherit;height: 140px;position: absolute; z-index: 1000;"></div>
                                <object class="flashobj" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
                                        id="utv510050"
                                        style="width: inherit;height: inherit; z-index: -1000;">
                                    <param name="flashvars"
                                           value="autoplay=false&amp;brand=embed&amp;cid={{ stream.ustream_uid }}"/>
                                    <param name="allowfullscreen" value="true"/>
                                    <param name="allowscriptaccess" value="always"/>
                                    <param name="movie" value="http://www.ustream.tv/flash/viewer.swf"/>
                                    <embed flashvars="autoplay=false&amp;brand=embed&amp;cid={{ stream.ustream_uid }}"
                                           allowfullscreen="true" allowscriptaccess="always"
                                           id="{{ stream.ustream_uid }}embed"
                                           name="utv_n_41439" src="http://www.ustream.tv/flash/viewer.swf"
                                           type="application/x-shockwave-flash"
                                           style="width: inherit;height: inherit;"/>
                                </object>
                            </div>
                            <div class="clear"></div>
                            <p><a class="colr2 stream_link"
                                  href="http://www.ustream.tv/embed/{{ stream.ustream_uid }}">{{ stream.title }}
                            </a></p>

                            <p class="viewcounts">Location: {{ stream.location_description }}</p>

                            <p class="by">Emergency Contact: {{ stream.emergency_contact }}</p>

                            <div class="clear"></div>


                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="clear"></div>
        </div>
        <div class="col2">
           		<h2 class="heading">Twitter Feed</h2>
              		<div class="sideblock">
               			<a class="twitter-timeline" href="https://twitter.com/Crowdcams" data-widget-id="458026112870658048">Tweets by @Crowdcams</a>
                        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
              		<div class="clear"></div>
              </div>
              <!--Feature Vedio -->
        </div>
        <div class="clear"></div>
        <!-- movie ads-->
        <img name="btn_list" class="all_icon" style=" width: 10%;height: 10%;" onclick="window.location.href='/list'"
             src="{% static 'images/all_icon.png' %}">
        <script type="application/javascript">
            $('.light_div').mousedown(function (e) {
                var curr_div = $(e.target);
                window.location.href='/view/?vid='+curr_div.data('uid');
                /*$.fancybox.open({
                    href: 'http://www.ustream.tv/embed/' + curr_div.data('uid'),
                    type: 'iframe',
                    afterLoad: function () {
                        suffix = '<h3>' + curr_div.data('title') + '</h3>' +
                                '<h4>Location: ' + curr_div.data('loc') + '</h4>' +
                                '<h4>Emergency Contact: ' + curr_div.data('contact') + '</h4>';
                        $(suffix).appendTo(this.inner)
                    }
                })*/
            })
        </script>
    </div>
{% endblock %}

templates/listing.html
{% extends "base_template.html" %}

{% block content %}
    {% load static %}
    <!--Content Sec -->
    <div id="content_sec">
        <!--Main Section-->
        <div class="col1">
            <!--Vedio slider -->
            <h2 class="heading"> All Available Locations</h2>

            <div class="listcontainer" id="accordion">
                {% for section,streams in sections.items %}
                    <h3>{{ section }}</h3>
                    <div>
                        <ul>
                            {% for stream in streams %}
                                <li>
                                    <div class="vediodiv">
                                        <div class="light_div"
                                             data-title="{{ stream.title }}"
                                             data-uid="{{ stream.ustream_uid }}"
                                             data-loc="{{ stream.location_description }}"
                                             data-contact="{{ stream.emergency_contact }}"
                                             style="width: inherit;height: 140px;position: absolute; z-index: 1000;"></div>
                                        <object class="flashobj" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
                                                id="utv510050"
                                                style="width: inherit;height: inherit; z-index: -1000;">
                                            <param name="flashvars"
                                                   value="autoplay=false&amp;brand=embed&amp;cid={{ stream.ustream_uid }}"/>
                                            <param name="allowfullscreen" value="true"/>
                                            <param name="allowscriptaccess" value="always"/>
                                            <param name="movie" value="http://www.ustream.tv/flash/viewer.swf"/>
                                            <embed flashvars="autoplay=false&amp;brand=embed&amp;cid={{ stream.ustream_uid }}"
                                                   allowfullscreen="true" allowscriptaccess="always"
                                                   id="{{ stream.ustream_uid }}embed"
                                                   name="utv_n_41439" src="http://www.ustream.tv/flash/viewer.swf"
                                                   type="application/x-shockwave-flash"
                                                   style="width: inherit;height: inherit;"/>
                                        </object>
                                    </div>
                                    <div class="stream_details">
                                        <h3><a class="colr2 stream_link fancybox.iframe"
                                               href="http://www.ustream.tv/embed/{{ stream.ustream_uid }}">{{ stream.title }}
                                        </a></h3>

                                        <p>Location: {{ stream.location_description }}</p>

                                        <p>Emergency Contact: {{ stream.emergency_contact }}</p>
                                    </div>
                                    <div class="clear"></div>

                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
        <!-- movie ads-->
        <script type="application/javascript">
            $('.light_div').mousedown(function (e) {
                var curr_div = $(e.target);
                $.fancybox.open({
                    href: 'http://www.ustream.tv/embed/' + curr_div.data('uid'),
                    type: 'iframe',
                    afterLoad: function () {
                        suffix = '<h3>' + curr_div.data('title') + '</h3>' +
                                '<h4>Location: ' + curr_div.data('loc') + '</h4>' +
                                '<h4>Emergency Contact: ' + curr_div.data('contact') + '</h4>';
                        $(suffix).appendTo(this.inner)
                    }
                })
            })
        </script>
    </div>
{% endblock %}

templates/login.html
{% extends "base_template.html" %}

{% block content %}
    {% load static %}

    <!--
{% endblock %}

templates/ourvision.html
{% extends "base_template.html" %}

{% block content %}
    {% load static %}
    <!--Content Sec -->
    <div id="content_sec">
        <!--Main Section-->
        <div class="container" id="written_content">
            <div class="interior">

                <div class="group2" style="padding-top: 0px;margin-top: 0px">
                    <p><i style="color: #000000">Envisioning a world where crime is nipped in the bud by the collaborative efforts of it's citizens</i></p>
                </div>
                <h2 style="font-size:24px">Going forward</h2>
                <div class="group2">
                    <p class="small_type">&nbsp;&nbsp;&nbsp;&nbsp; Integrating more commercially available streaming platforms. Creating user accounts for keeping track of positive karma and much more. Seeking Institutional support to put Crowdcams at places of significance. Looking for fresh and thrilling ideas.
                    </p>
                </div>
                <h2 style="font-size:24px">Give Us Feedback</h2>
                <div class="group2">
                    <p class="small_type">&nbsp;&nbsp;&nbsp;&nbsp;We are ardently looking for your feedback. If you have any suggestion or an idea to share, we would be glad to hear it. Reach out to us at <a href="mailto:support@crowdcams.org">support@crowdcams.org</a> or visit the Feedback and Support Link at the right of this page.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}